{
 "title": "experiment",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "netdev",
    "label": "netdev",
    "query": "label_values(node_network_receive_bytes_total, device)"
   },
   { "name": "interval", "query": "15s, 30s, 1m,10m" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(node_network_receive_bytes_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "net throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\", device=~\"$netdev\"}[$interval]) * 8\n +\nirate(node_network_transmit_bytes_total[$interval]) * 8",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "avg cpu util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by (instance) (irate(node_cpu_seconds_total{instance=~\"$instance\", mode=\"idle\"}[$interval]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "mem util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}